### ISSUE TITLE
Gratipay merge

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.org#32]
[en] In https://github.com/gratipay/inside.gratipay.com/issues/1196 @whit537 has proposed "merging" Gratipay into Liberapay. Concretely, as far as the Liberapay organization is concerned, this would mean acquiring assets from Gratipay at a symbolic price. We haven't made a detailed list of assets but the main one is obviously the database, then the domain names, the Twitter account, etc.

[fr] Dans https://github.com/gratipay/inside.gratipay.com/issues/1196 @whit537 a proposé "l'intégration" de Gratipay dans Liberapay. Concrètement, en ce qui concerne l'association Liberapay, cela revient à acheter certaines choses qui appartiennent à Gratipay, à un prix symbolique. Nous n'avons pas fait de liste détaillée mais la ressource principale est évidemment la base de données, puis les noms de domaines, le compte Twitter, etc.

**Comment by Zatalyz** [comment]
**[fr]**Ils ont accompli énormément de travail au fil des ans et ce serait évidement profitable de pouvoir s'appuyer dessus. Cela évitera aussi que leur nom de domaine et compte twitter se fasse squatter, ce qui sera une bonne chose. Enfin j'adore leur pièce percée d'un cœur et en les rachetant, cela permet de réutiliser cette image dans de bonnes conditions. 

Un seul bémol concernant la base utilisateur, avant de l'intégrer chez nous (si c'est envisageable). Je préfère vraiment que chaque utilisateur confirme qu'il accepte que ses données soient transférées sur Liberapay ; sinon nous devons nous interdire d'utiliser ce genre de données. Cela ne s'oppose pas à un rachat, mais c'est un aspect éthique qui me semble essentiel. 

Ensuite, tout dépend du prix et de combien on a sur le compte. Si ces questions matérielles ne posent pas souci, je suis pour ce merge. 

**[en]**They have done a great deal of work over the years and it would obviously be beneficial to build on that. This will also prevent their domain name and twitter account from being squatted, which will be a good thing. Finally, I love their piece pierced with a heart and by buying them back, it makes it possible to reuse this image in good conditions. 

Only one downside concerning the user base, before integrating it with us (if possible). I really prefer it if every user confirms that they agree to their data being transferred to Liberapay; otherwise, we must refrain from using this kind of data. This does not preclude a buyback, but it is an ethical aspect that I think is essential. 

Then it all depends on the price and how much you have in the account. If these material matters are not of concern, I am for this merge.

**Comment by Changaco** [comment]
[en] It's been two weeks, I count two in favor (me and @Zatalyz) and no objections, so we're good to go.

[fr] Deux semaines se sont écoulées, je compte deux votes pour (moi et @Zatalyz) et aucune objection, donc le principe du "rachat" de Gratipay est validé.

**Comment by Changaco** [comment]
(J'ai bien noté ton bémol @Zatalyz, on demande actuellement une confirmation avant de créer un compte Liberapay à partir des données de Gratipay.)

**Comment by Changaco** [comment]
Vote on the Gratipay side: <https://github.com/gratipay/inside.gratipay.com/issues/1217>.
